Document: steamcmddl
Title: Debian steamcmddl Manual
Author: <insert document author here>
Abstract: This manual describes what steamcmddl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/steamcmddl/steamcmddl.sgml.gz

Format: postscript
Files: /usr/share/doc/steamcmddl/steamcmddl.ps.gz

Format: text
Files: /usr/share/doc/steamcmddl/steamcmddl.text.gz

Format: HTML
Index: /usr/share/doc/steamcmddl/html/index.html
Files: /usr/share/doc/steamcmddl/html/*.html
